Repository GastonVidart/tdd-bowling, pull requests merged in 2020-06, with the labels that each got.

#1 Todos ceros
  .vscode/settings.json
  src/bowling.py
  test_bowling.py
Labels: enhancement

#3 Feature todo 1
  src/bowling.py
  test_bowling.py
Labels: enhancement

#6 Feature strike
  src/bowling.py
  test_bowling.py
Labels: enhancement

#8 Feature mezcla strike spare
  test_bowling.py
Labels: test_nuevo

#9 Nueva Versión v0.3
  src/bowling.py
  test_bowling.py
Labels: enhancement

#10 Feature fin ronda 10
  README.md
  src/bowling.py
  test_bowling.py
Labels: enhancement

#11 test VERDE all strike
  src/bowling.py
  test_bowling.py
Labels: enhancement

#12 Deploy
  README.md
  src/bowling.py
  test_bowling.py
Labels: enhancement

#13 Feature fix
  src/bowling.py
  test_bowling.py
Labels: enhancement

#15 Feature readme
  README.md
  img/test_cuarto_ciclo.png
  img/test_primer_ciclo.png
  img/test_quinto_ciclo.png
  img/test_rojo_1.png
  img/test_rojo_2.png
  img/test_segundo_ciclo.png
  img/test_septimo_ciclo.png
  img/test_sexto_ciclo_1.png
  img/test_sexto_ciclo_2.png
  img/test_sexto_ciclo_3.png
  img/test_sexto_ciclo_4.png
  img/test_sexto_ciclo_5.png
  img/test_tercer_ciclo.png
  img/test_verde.png
Labels: documentation

#16 Entrega Final v1.1
  README.md
  img/test_cuarto_ciclo.png
  img/test_primer_ciclo.png
  img/test_quinto_ciclo.png
  img/test_rojo_1.png
  img/test_rojo_2.png
  img/test_segundo_ciclo.png
  img/test_septimo_ciclo.png
  img/test_sexto_ciclo_1.png
  img/test_sexto_ciclo_2.png
  img/test_sexto_ciclo_3.png
  img/test_sexto_ciclo_4.png
  img/test_sexto_ciclo_5.png
  img/test_tercer_ciclo.png
  img/test_verde.png
  src/bowling.py
  test_bowling.py
Labels: documentation, enhancement
